### ISSUE TITLE
Is CatGDP asleep?

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [tipani86/CatGDP#21]
![Capture](https://github.com/tipani86/CatGDP/assets/40564064/6b924b3e-6ee6-454e-b522-69a98c1442c8)

**Comment by tipani86** [comment]
Oh no @Claire-Eleutheriane! Seems my Stable Diffusion tokens ran out. They have to be replenished manually and I didn't expect people to go through $10 worth of tokens in less than a month! I am adding more right now!

**Comment by Claire-Eleutheriane** [comment]
Great! :heart_eyes:
